# Day 64

try:
    print(x)
except:
    print('Error')
